// src/components/StarRating.tsx
import { useState } from 'react'

/**
 * 0–10 internal scale rendered as 5 stars (half-star steps).
 */
export function StarRating({
  value,
  onChange,
  readOnly = false,
  size = 18,
}: {
  value: number | null | undefined
  onChange?: (v: number | null) => void
  readOnly?: boolean
  size?: number
}) {
  const [hover, setHover] = useState<number | null>(null)
  const display = hover ?? value ?? 0
  const stars = [1, 2, 3, 4, 5]

  function handleClick(starIdx: number, half: boolean) {
    if (readOnly || !onChange) return
    const next = starIdx * 2 - (half ? 1 : 0)
    onChange(value === next ? null : next)
  }

  return (
    <div className="inline-flex items-center gap-0.5" aria-label={`Rating ${value ?? 0}/10`}>
      {stars.map((s) => {
        const filled = display >= s * 2
        const half = !filled && display >= s * 2 - 1
        return (
          <span
            key={s}
            className="relative inline-block"
            style={{ width: size, height: size }}
            onMouseLeave={() => setHover(null)}
          >
            {/* base outline */}
            <Star size={size} className="text-line dark:text-line-dark" />
            {(filled || half) && (
              <span
                className="absolute inset-0 overflow-hidden"
                style={{ width: half ? size / 2 : size }}
              >
                <Star size={size} className="text-accent" filled />
              </span>
            )}
            {!readOnly && (
              <>
                <button
                  type="button"
                  className="absolute inset-y-0 left-0 w-1/2 cursor-pointer"
                  aria-label={`Set rating to ${s * 2 - 1}`}
                  onMouseEnter={() => setHover(s * 2 - 1)}
                  onClick={() => handleClick(s, true)}
                />
                <button
                  type="button"
                  className="absolute inset-y-0 right-0 w-1/2 cursor-pointer"
                  aria-label={`Set rating to ${s * 2}`}
                  onMouseEnter={() => setHover(s * 2)}
                  onClick={() => handleClick(s, false)}
                />
              </>
            )}
          </span>
        )
      })}
      {value != null && (
        <span className="ml-1.5 text-xs text-ink-muted dark:text-ink-dark-muted">{(value / 2).toFixed(1)}</span>
      )}
    </div>
  )
}

function Star({ size, className, filled }: { size: number; className: string; filled?: boolean }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      className={className}
      fill={filled ? 'currentColor' : 'none'}
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinejoin="round"
    >
      <path d="M12 17.3 5.82 21l1.64-7.03L2 9.24l7.19-.62L12 2l2.81 6.62 7.19.62-5.46 4.73L18.18 21z" />
    </svg>
  )
}

// angular/src/app/components/star-rating/star-rating.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output, signal } from '@angular/core';

@Component({
  selector: 'app-star-rating',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="inline-flex items-center gap-0.5" [attr.aria-label]="'Rating ' + (value ?? 0) + '/10'">
      @for (s of stars; track s) {
        <span
          class="relative inline-block"
          [style.width.px]="size"
          [style.height.px]="size"
          (mouseleave)="hover.set(null)"
        >
          <svg
            viewBox="0 0 24 24"
            [attr.width]="size"
            [attr.height]="size"
            class="text-line dark:text-line-dark"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linejoin="round"
          >
            <path d="M12 17.3 5.82 21l1.64-7.03L2 9.24l7.19-.62L12 2l2.81 6.62 7.19.62-5.46 4.73L18.18 21z" />
          </svg>
          @if (filled(s) || half(s)) {
            <span class="absolute inset-0 overflow-hidden" [style.width.px]="half(s) ? size / 2 : size">
              <svg
                viewBox="0 0 24 24"
                [attr.width]="size"
                [attr.height]="size"
                class="text-accent"
                fill="currentColor"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linejoin="round"
              >
                <path d="M12 17.3 5.82 21l1.64-7.03L2 9.24l7.19-.62L12 2l2.81 6.62 7.19.62-5.46 4.73L18.18 21z" />
              </svg>
            </span>
          }
          @if (!readOnly) {
            <button
              type="button"
              class="absolute inset-y-0 left-0 w-1/2 cursor-pointer"
              [attr.aria-label]="'Set rating to ' + (s * 2 - 1)"
              (mouseenter)="hover.set(s * 2 - 1)"
              (click)="handleClick(s, true)"
            ></button>
            <button
              type="button"
              class="absolute inset-y-0 right-0 w-1/2 cursor-pointer"
              [attr.aria-label]="'Set rating to ' + (s * 2)"
              (mouseenter)="hover.set(s * 2)"
              (click)="handleClick(s, false)"
            ></button>
          }
        </span>
      }
      @if (value != null) {
        <span class="ml-1.5 text-xs text-ink-muted dark:text-ink-dark-muted">{{ (value / 2).toFixed(1) }}</span>
      }
    </div>
  `,
})
export class StarRatingComponent {
  @Input() value: number | null | undefined = null;
  @Input() readOnly = false;
  @Input() size = 18;
  @Output() valueChange = new EventEmitter<number | null>();

  hover = signal<number | null>(null);
  stars = [1, 2, 3, 4, 5];

  private display(): number {
    return this.hover() ?? this.value ?? 0;
  }

  filled(s: number): boolean {
    return this.display() >= s * 2;
  }

  half(s: number): boolean {
    return !this.filled(s) && this.display() >= s * 2 - 1;
  }

  handleClick(starIdx: number, half: boolean) {
    if (this.readOnly) return;
    const next = starIdx * 2 - (half ? 1 : 0);
    this.valueChange.emit(this.value === next ? null : next);
  }
}
